### ISSUE TITLE
Minimum viable lesson metadata

### ISSUE THREAD

**Issue by Skelehog** [BetterJapanese/betterjapanese#6]
```
id: <number>
title: <string>
version:
  major: <number>
  minor: <number>
  patch: <number>
cards: [card.id]
```
